### ISSUE TITLE
DataStore plugin not added correctly

### ISSUE THREAD

**Issue by sinene** [AW5th/MBM-March#29]

**Comment by nickowalcz** [comment]
Not having this issue on my end 

Possible solution: add this to your amplifyconfiguration.dart 
   
 "dataStore": {
        "plugins": {
            "awsDataStorePlugin": {
                "syncMode": "api",
                "apiName": "amplifyDatasource"
            }
        }
    },

**Comment by sinene** [comment]
Still having issue:
Tried "flutter pub add amplify_datastore" in the console([source](https://pub.dev/packages/amplify_datastore/install))
Result: Could not find a subcommand named "add" for "flutter pub".

Tried "amplify pull"
Result: Same error

[Source](https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/js#how-it-works) directs to use amplify add auth or amplify add function. Tried "amplify add function". 
Result: Was just adding lambda functions(we're going to use those but not yet)

Tried "amplify update api
Result: Gave me the option to remove datastore indicating that datastore is indeed in our api

Looked at our schema at C:\Users\Inene\AndroidStudioProjects\MBM-March2\amplify\backend\api\MBM\schema.graphql 
Did not find anything wrong

[Source ](https://github.com/aws-amplify/amplify-android/issues/384) gives steps on how to manually patch the config file
Result:
-Noticed "apiName" in "datastore" doesn't match with "api" like it does in the example provided by the source.
Note: Our backend is called "MBM", 
-Renamed "apiName" to "MBM" and pushed the changes to the amplifyconfig file to the backend

According to [source](https://docs.amplify.aws/cli/graphql-transformer/codegen#statement-depth), the **amplify add codegen** allows you to add AppSync API created using the AWS console.
Under "Integrate with your app" in the[ AWS AppSync console ](https://us-east-1.console.aws.amazon.com/appsync/home?region=us-east-1#/f7z2hkxc4vav3isx7gjf6mwjly/v1/home)for MBM-staging, instructs to use:
amplify add codegen --apiId f7z2hkxc4vav3isx7gjf6mwjly from  MBM staging
Result: 
    Got "Unexpected token } in JSON at position 3067" error
   -looked through all the JSON files in the project

Started 6:13pm
Ended 9:40pm

**Comment by nickowalcz** [comment]
5:10 
Succesfully logged in using username test@test.com with password1234. 
Encountered error 'DataStore plugin not added correctly' when pressing edm button

5:25 
Found additional documentation on setting up aws datastore
https://www.raywenderlich.com/12942091-using-aws-as-a-back-end-the-data-store-api

5:30 
when running 'amplify api add' directed to run 'amplify update api'
when running 'amplify update api' and selecting 'GraphQL' prints following

1.Walkthrough all configurations
2. update auth settings
3. Disable datastore for entire API

Initially seems like datastore is apart of the project despite it missing from the podfile and errors occuring

Will research more info on debugging datastore plugin not found currently LARGE setback

Researched how to store objects into datastore on amplify tutorial

hours: 2h 20 min

**Comment by nickowalcz** [comment]
Researched implementing datastore off the AWS wesbite still encountering plugin not found. Will focus on S3 storage tomorrow.
1H 40 min

**Comment by sinene** [comment]
Nick: So the edm button still doesn’t work but it stopped giving me the datastore plug-in not found when I added Amplify.DataStore.addPlugin(dataStorePlugin)
